version: 2.1

jobs:
  build:
    docker:
      - image: cirlceci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            echo $(circleci tests glob "foo/**/*" "bar/**/*")
            cirlceci tests glob "foo/**/*" "bar/**/*" | xargs -n 1 echo
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud